
```{r setup, echo = FALSE, include = FALSE}
library("papaja")
library("knitr") # for knitting things
library("tidyverse") # for all things tidyverse
library("car")
library("lme4")
library("patchwork")
library("effsize")

# these options here change the formatting of how comments are rendered
opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")

# set the default ggplot theme 
theme_set(theme_classic())
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r loading data M, warning=FALSE, include=F}
df.resp_M <- read.csv("../../data/responding/data_CN.csv") %>%
  select(-X)

# check for participants who completed the entire experiment. Because the experiment is
# quite long, some participants decide to come back afterwards, so there are a few files
# that are recorded as incomplete. 
df.ppts_finished_M <- df.resp_M %>% 
  group_by(subject) %>%
  summarize(finished = ifelse("demo-final" %in% unique(variable_type), "yes", "no")) %>%
  filter(finished == "yes")

df.ppts_not_finished_M <- df.resp_M %>% 
  group_by(subject) %>%
  summarize(finished = ifelse("demo-final" %in% unique(variable_type), "yes", "no")) %>%
  filter(finished == "no")

df.resp_M <- df.resp_M %>%
  filter(subject %in% df.ppts_finished_M$subject) 

df.ppts_att_M <- df.resp_M %>%
  filter(stim_type == "attention check") %>%
  mutate(correct_response = strsplit(cue, "选择")) %>%
  mutate(correct_response = sapply(correct_response, "[[", 2)) %>%
  mutate(correct_response = str_replace_all(correct_response, "“", "")) %>%
  mutate(correct_response = str_replace_all(correct_response, "”", "")) %>%
  mutate(pass_att_check = ifelse(responses == correct_response, 1, 0)) %>%
  group_by(subject) %>%
  summarize(pass_att_check_percent = mean(pass_att_check)) %>%
  filter(pass_att_check_percent >= 0.8)

df.resp_M <- df.resp_M %>%
  filter(subject %in% df.ppts_att_M$subject) 

ppts_resp_M <- unique(df.resp_M$subject)
```

```{r}
df.demog <- read.csv("../../data/responding/data_demog.csv") %>%
  select(-X) %>%
  filter(country == "CN")
```


```{r exclusion E, include = F, warning = F}
#non-native speaker
df.ppts_non_native_lang_M <- df.demog %>%
  filter(demog_question == "firstlanguage" & demog_response == "不是")

ppts_non_native_lang_M = unique(df.ppts_non_native_lang_M$subject) #3
percent_dropped = length(intersect(ppts_non_native_lang_M, ppts_resp_M)) / length(ppts_resp_M)
percent_dropped #0.01086

#fluent in Vietnamese & Mandarin
df.lang_sp_vi_M <- df.demog %>%
  filter(demog_question == "lang_sp_vi" & demog_response > 4)

df.lang_ud_vi_M <- df.demog %>%
  filter(demog_question == "lang_ud_vi" & demog_response > 4)

df.lang_vi_M <- inner_join(df.lang_sp_vi_M, df.lang_ud_vi_M, by = 'subject')
         
ppts_vi_speaker_M = unique(df.lang_vi_M$subject) #1
percent_dropped = length(intersect(ppts_vi_speaker_M, ppts_resp_M)) / length(ppts_resp_M)
percent_dropped #0

df.lang_sp_en_M <- df.demog %>%
  filter(demog_question == "lang_sp_en" & demog_response > 4)

df.lang_ud_en_M <- df.demog %>%
  filter(demog_question == "lang_ud_en" & demog_response > 4)

df.lang_en_M <- inner_join(df.lang_sp_en_M, df.lang_ud_en_M, by = 'subject')

ppts_en_speaker_M = unique(df.lang_en_M$subject) #74
percent_dropped = length(intersect(ppts_en_speaker_M, ppts_resp_M)) / length(ppts_resp_M)
percent_dropped #0.375 # do not use this criterion

#have lived outside the sample country for more than 2 years
df.lived_abroad_M <- df.demog %>%
  filter(demog_question == "abroadexp" & demog_response == "是")

ppts_lived_abroad_M = unique(df.lived_abroad_M$subject) #40
percent_dropped = length(intersect(ppts_lived_abroad_M, ppts_resp_M)) / length(unique(df.resp_M$subject))
percent_dropped #0.163043

#have travelled extensively (more than 6 international experiences of 2 days or longer)
df.oversea_exp_M <- df.demog %>%
  filter(demog_question == "overseaexpnum" & demog_response == "六段或更多国际经历")

ppts_oversea_exp_M = unique(df.oversea_exp_M$subject) #12
percent_dropped = length(intersect(ppts_oversea_exp_M, ppts_resp_M)) / length(unique(df.resp_M$subject))
percent_dropped #0.0434782 

df.resp_M <- df.resp_M %>%
  filter(!(subject %in% ppts_non_native_lang_M),
         !(subject %in% ppts_vi_speaker_M), 
         !(subject %in% ppts_lived_abroad_M), 
         !(subject %in% ppts_oversea_exp_M))

length(unique(df.resp_M$subject)) #149
```

```{r}
write.csv(df.resp_M, "../../data/responding/dataCN_excl.csv")
```

