
```{r setup, echo = FALSE, include = FALSE}
library("papaja")
library("knitr") # for knitting things
library("tidyverse") # for all things tidyverse
library("car")
library("lme4")
library("patchwork")
library("effsize")

# these options here change the formatting of how comments are rendered
opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")

# set the default ggplot theme 
theme_set(theme_classic())
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r loading data M, warning=FALSE, include=F}
df.resp_M <- read.csv("../../data/responding/data_CN.csv") %>%
  select(-X)

# check for participants who completed the entire experiment. Because the experiment is
# quite long, some participants decide to come back afterwards, so there are a few files
# that are recorded as incomplete. 
df.ppts_finished_M <- df.resp_M %>% 
  group_by(subject) %>%
  summarize(finished = ifelse("demo-final" %in% unique(variable_type), "yes", "no")) %>%
  filter(finished == "yes")

df.ppts_not_finished_M <- df.resp_M %>% 
  group_by(subject) %>%
  summarize(finished = ifelse("demo-final" %in% unique(variable_type), "yes", "no")) %>%
  filter(finished == "no")

df.resp_M <- df.resp_M %>%
  filter(subject %in% df.ppts_finished_M$subject) 

df.ppts_att_M <- df.resp_M %>%
  filter(stim_type == "attention check") %>%
  mutate(correct_response = strsplit(cue, "选择")) %>%
  mutate(correct_response = sapply(correct_response, "[[", 2)) %>%
  mutate(correct_response = str_replace_all(correct_response, "“", "")) %>%
  mutate(correct_response = str_replace_all(correct_response, "”", "")) %>%
  mutate(pass_att_check = ifelse(responses == correct_response, 1, 0)) %>%
  group_by(subject) %>%
  summarize(pass_att_check_percent = mean(pass_att_check)) %>%
  filter(pass_att_check_percent == 1.0)

df.resp_M <- df.resp_M %>%
  filter(subject %in% df.ppts_att_M$subject) 
```

```{r exclusion M, include = F, warning = F}
#non-native speaker
split_responses_demog <- function(responses) {
  responses <- as.character(responses)
  response_list <- unlist(strsplit(responses, ',|:'))
  response_list <- response_list[seq(1, length(response_list))]
  response_list <- gsub("}", "", response_list)
  response_list <- gsub("\"", "", response_list)
  return(response_list)
}

NATIVE_LANG = 2
get_native_lang <- Vectorize(function(responses) {
  responses <- split_responses_demog(responses)
  if(responses[NATIVE_LANG-1] != "{firstlanguage") 
    {warnings("cannot find native language answer")}
  else
    {return (responses[NATIVE_LANG])}
})

df.ppts_non_native_lang_M <- df.resp_M %>%
  select(subject, responses, variable_type) %>%
  filter(variable_type == "demog_language") %>%
  mutate(native_speaker = get_native_lang(responses)) %>%
  filter(native_speaker == "不是")

ppts_non_native_lang_M = unique(df.ppts_non_native_lang_M$subject) #2
percent_dropped = length(ppts_non_native_lang_M) / length(unique(df.resp_M$subject))
percent_dropped #0.01398601

#fluent in English
SPEAKER = 2
SPEAKING = 23
UNDERSTANDING = 46

get_speaker <- Vectorize(function(responses) {
  responses <- split_responses_demog(responses)
  return (responses[SPEAKER])
})

get_fluency_speaking <- Vectorize(function(responses) {
  responses <- split_responses_demog(responses)
  return (responses[SPEAKING])
})

get_fluency_understanding <- Vectorize(function(responses) {
  responses <- split_responses_demog(responses)
  return (responses[UNDERSTANDING])
})

df.lang_en_M <- df.resp_M %>%
  select(subject, responses, variable_type) %>%
  filter(variable_type == "demog_language_en") %>%
  mutate(en_speaker = get_speaker(responses))
  
df.lang_en_fluency_M <- df.resp_M %>%
  select(subject, responses, variable_type) %>%
  filter(variable_type == "demog_conditional_language_en_fluency") %>%
  mutate(en_fluency_sp = as.numeric(get_fluency_speaking(responses))) %>%
  mutate(en_fluency_ud = as.numeric(get_fluency_understanding(responses)))

df.lang_en_M <- full_join(df.lang_en_M, 
                          df.lang_en_fluency_M, 
                          by = "subject") %>%
  select(subject, en_speaker, en_fluency_sp, en_fluency_ud) %>%
  filter(en_speaker == "能",
         en_fluency_sp > 4, 
         en_fluency_ud > 4)

ppts_en_speaker_M = unique(df.lang_en_M$subject) #50
percent_dropped = length(ppts_en_speaker_M) / length(unique(df.resp_M$subject))
percent_dropped #0.3496503 # will not use this criterion

df.lang_vi_M <- df.resp_M %>%
  select(subject, responses, variable_type) %>%
  filter(variable_type == "demog_language_vi") %>%
  mutate(vi_speaker = get_speaker(responses))
  
df.lang_vi_fluency_M <- df.resp_M %>%
  filter(variable_type == "demog_conditional_language_vi_fluency") %>%
  mutate(vi_fluency_sp = as.numeric(get_fluency_speaking(responses))) %>%
  mutate(vi_fluency_ud = as.numeric(get_fluency_understanding(responses)))

df.lang_vi_M <- full_join(df.lang_vi_M, 
                          df.lang_vi_fluency_M, 
                          by = "subject") %>%
  select(subject, vi_speaker, vi_fluency_sp, vi_fluency_ud) %>%
  filter(vi_speaker == "能",
         vi_fluency_sp > 4, 
         vi_fluency_ud > 4)

ppts_vi_speaker_M = unique(df.lang_vi_M$subject) #50
percent_dropped = length(ppts_vi_speaker_M) / length(unique(df.resp_M$subject))
percent_dropped #0

#have lived outside the sample country for more than 2 years
#have travelled extensively (more than 6 international experiences of 2 days or longer) 
YEARSABROAD = 2
OVERSEAEXP = 4

get_lived_abroad <- Vectorize(function(responses) {
  responses <- split_responses_demog(responses)
  return (responses[YEARSABROAD])
})

get_oversea_exp <- Vectorize(function(responses) {
  responses <- split_responses_demog(responses)
  return (responses[OVERSEAEXP])
})

df.abroad_M <- df.resp_M %>%
  select(subject, responses, variable_type) %>%
  filter(variable_type == "demog_oversea_experience") %>%
  mutate(lived_abroad = get_lived_abroad(responses)) %>%
  mutate(oversea_exp = get_oversea_exp(responses))

df.lived_abroad_M <- df.abroad_M %>%
  filter(lived_abroad == "是")

ppts_lived_abroad_M = unique(df.lived_abroad_M$subject) #23
percent_dropped = length(ppts_lived_abroad_M) / length(unique(df.resp_M$subject))
percent_dropped # 0.1608392

df.oversea_exp_M <- df.abroad_M %>%
  filter(oversea_exp == "六段或更多国际经历")

ppts_oversea_exp_M = unique(df.oversea_exp_M$subject) #0
percent_dropped = length(ppts_oversea_exp_M) / length(unique(df.resp_M$subject))
percent_dropped #0 

df.resp_M <- df.resp_M %>%
  filter(!(subject %in% ppts_non_native_lang_M),
         !(subject %in% ppts_lived_abroad_M),
         !(subject %in% ppts_vi_speaker_M),
         !(subject %in% ppts_oversea_exp_M),)

length(unique(df.resp_M$subject)) 
```

```{r}
write.csv(df.resp_M, "../../data/responding/dataCN_excl.csv")
```

