```{r setup, echo = FALSE, include = FALSE}
library("papaja")
library("knitr") # for knitting things
library("tidyverse") # for all things tidyverse
library("car")
library("lme4")
library("patchwork")
library("effsize")
library("Hmisc")
library("dplyr")


# these options here change the formatting of how comments are rendered
opts_chunk$set(
  comment = "",
  results = "hold",
  fig.show = "hold")

# set the default ggplot theme 
theme_set(theme_classic())

r_refs("r-references.bib")
r_refs("references/packages.bib")

```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r read in data}
df <- read.csv("../../data/data_USCNVN_ENZHVI_assoc_strength.csv")
triads_omit_assoc <- read.csv("../../data/triads_omit_assoc.csv") %>%
  pull(x)
triads_omit_freq <- read.csv("../../data/triads_omit.csv") %>%
  pull(x)
```

```{r change NA to epsilon}
df <- df %>%
  mutate(tax_match_assoc_strength_E = ifelse(is.na(tax_match_assoc_strength_E), 
                                  .Machine$double.eps, tax_match_assoc_strength_E),
         theme_match_assoc_strength_E = ifelse(is.na(theme_match_assoc_strength_E), 
                                  .Machine$double.eps, theme_match_assoc_strength_E)) %>%
  mutate(theme_assoc_strength_prop_E = theme_match_assoc_strength_E / (theme_match_assoc_strength_E + tax_match_assoc_strength_E))
```

# Correlation between assoc strength prediction and response data
```{r}
df.cue_country_freq <- df %>%
  group_by(triad, country, theme_match_assoc_strength_E) %>%
  dplyr::summarize(emp_theme_prop = mean(responses_theme))
ggplot(data = df.cue_country_freq %>% filter(country == "US"), 
        mapping = aes(x = emp_theme_prop, 
                     y = theme_match_assoc_strength_E,
                     label = triad)) +
   geom_text() + 
   geom_smooth(method = "lm") +
   labs(x = "Proportion Thematic Chosen (US)", 
        y = "Proportion Thematic Predicted by Assoc Strength (English)") + 
  theme(axis.title = element_text(size=rel(0.75)))
```

# Does adding association improve the model?
```{r US responding predicted by each corpus model raw co-occurrences, warning=FALSE}
# English 
fit.EN_US = glmer(responses_theme ~ theme_freq_prop_E + (1 | subject) + (1 | triad), 
          data = df %>% filter(country == "US", 
                               !(triad %in% triads_omit_assoc),
                               !(triad %in% triads_omit_freq)), 
          family="binomial")
summary(fit.EN_US)
fit.EN_US.anova = Anova(fit.EN_US, type = 3)

fit.EN_US.anova

# English with association strengths
fit.EN_US_assoc = glmer(responses_theme ~ theme_freq_prop_E + theme_match_assoc_strength_E + (1 | subject) + (1 | triad), 
          data = df %>% filter(country == "US", 
                               !(triad %in% triads_omit_assoc),
                               !(triad %in% triads_omit_freq)), 
          family="binomial")
summary(fit.EN_US_assoc)
fit.EN_US_assoc.anova = Anova(fit.EN_US_assoc, type = 3)

fit.EN_US_assoc.anova

fit.EN_US_assoc_compare = anova(fit.EN_US, fit.EN_US_assoc, type = 3)
fit.EN_US_assoc_compare
```

Adding association strengths did not improve the model significantly.

# Does association strength predict response data?
```{r only association strengths}
# English 
fit.EN_US_assoc_only = glmer(responses_theme ~ theme_match_assoc_strength_E + (1 | subject) + (1 | triad), 
          data = df %>% filter(country == "US", 
                               !(triad %in% triads_omit_assoc),
                               !(triad %in% triads_omit_freq)), 
          family="binomial")
summary(fit.EN_US_assoc_only)
fit.EN_US_assoc_only.anova = Anova(fit.EN_US_assoc_only, type = 3)

fit.EN_US_assoc_only.anova

fit.EN_US_assoc_only_compare = anova(fit.EN_US, fit.EN_US_assoc_only, type = 3)
fit.EN_US_assoc_only_compare
```

Yes. 